version: '3.8'

services:
    track-nginx:
        image: nginx:1.21.6-alpine
        container_name: track-nginx
        restart: 'no'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx:/var/www/docker/nginx
            - ../frontend/build:/var/www/build
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - "net-track"
        depends_on:
            - "track-php"

    track-centrifugo:
        container_name: track-centrifugo
        image: centrifugo/centrifugo:v3.0.5
        volumes:
            - ./docker/centrifugo/config.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - 8000:8000
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        networks:
            - "net-track"
        links:
            - track-php

    track-php:
        build:
            context: docker/php
            dockerfile: dockerfile
        container_name: track-php
        restart: 'no'
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./docker/system/supervisor-listener.conf:/etc/supervisor/conf.d/supervisor-listener.conf
        networks:
            - "net-track"
        depends_on:
            - "track-postgres"

    track-postgres:
        image: postgres:latest
        container_name: track-postgres
        restart: 'no'
        environment:
            POSTGRES_DB: "track"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "pass"
        ports:
            - "5435:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        networks:
            - "net-track"


networks:
    net-track:
        driver: bridge

