version: '3.8'

services:
    track-nginx:
        image: nginx:1.21.6-alpine
        container_name: track-nginx
        restart: 'no'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx:/var/www/docker/nginx
            - ../frontend/build:/var/www/build
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - "net-track"
        depends_on:
            - "track-php"

    soketi:
        container_name: 'soketi_server'
        restart: unless-stopped
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: 'app-id'
            SOKETI_DEFAULT_APP_KEY: 'app-key'
            SOKETI_DEFAULT_APP_SECRET: 'app-secret'
            SOKETI_DEFAULT_APP_USER_AUTHENTICATION: 'true'
            SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: 'true'
        networks:
            - "net-track"



    track-php:
        build:
            context: docker/php
            dockerfile: dockerfile
        container_name: track-php
        restart: 'no'
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./docker/system/supervisor-listener.conf:/etc/supervisor/conf.d/supervisor-listener.conf
        networks:
            - "net-track"
        depends_on:
            - "track-postgres"

    track-postgres:
        image: postgres:latest
        container_name: track-postgres
        restart: 'no'
        environment:
            POSTGRES_DB: "track"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "pass"
        ports:
            - "5435:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        networks:
            - "net-track"


networks:
    net-track:
        driver: bridge

