version: '3.8'

services:
    track-nginx:
        image: nginx:1.21.6-alpine
        container_name: track-nginx
        restart: 'no'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - "net-track"
        depends_on:
            - "track-php"

    track-php:
        build:
            context: docker/php
            dockerfile: dockerfile
        container_name: track-php
        restart: 'no'
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - "net-track"
        depends_on:
            - "track-postgres"

    track-postgres:
        image: postgres:latest
        container_name: track-postgres
        restart: 'no'
        environment:
            POSTGRES_DB: "track"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "pass"
        ports:
            - "5435:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
        networks:
            - "net-track"


networks:
    net-track:
        driver: bridge

